### PR TITLE
Add delete Neighbor functionality

### PR DESCRIPTION
**Pull request by patnorris**
Relies on delete_bridge function implemented in Bebb Protocol (see updated interface file)

### CODE REVIEW

**Comment by tiusty** [comment]
Scanned through the code and looked good. Didn't seem like it was on the mainnet to test?

**Review by tiusty — APPROVED** [review]

**Comment by patnorris** [comment]
nice, thanks. No, I haven't deployed the latest PRs on the mainnet. We can think about a good process to release changes. Currently, it seems like our local setups match the mainnet relatively well, so I'm leaning towards first reviewing the changes locally, merging the PR and then deploying the main branch to the mainnet. In cases where the local setup doesn't seem to match the mainnet, we coul deviate from this process. What do you think?

**Comment by tiusty** [comment]
> nice, thanks. No, I haven't deployed the latest PRs on the mainnet. We can think about a good process to release changes. Currently, it seems like our local setups match the mainnet relatively well, so I'm leaning towards first reviewing the changes locally, merging the PR and then deploying the main branch to the mainnet. In cases where the local setup doesn't seem to match the mainnet, we coul deviate from this process. What do you think?

Generally agree but we can't test the neighborhood functionality locally unless we come up with a good way to add the bebb protocol locally

**Comment by patnorris** [comment]
I looked into running both Bebb Protocol and OIM locally on the same replica once again and found that it should work according to these sources:
https://forum.dfinity.org/t/use-the-same-local-replica-for-multiple-projects/11900/11
https://forum.dfinity.org/t/getting-exact-same-canister-ids-for-two-separate-projects-locally-and-they-share-ledger-funds-as-well/11504/6

I managed to deploy both projects to the same local replica, so making calls between the canisters work should just be a bit of trial and error. This issue addresses this: https://github.com/patnorris/PWS/issues/18

**Pull request merged**
