### PR TITLE
Add iframe security properties

### PR DESCRIPTION
**Pull request by patnorris**
Adds properties to iframes that should make them as secure as possible

To test:
All functionality should work as before
In particular, each view using iframes should work the same and not be affected by these changes

### CODE REVIEW

**Comment by tiusty** [comment]
image

I ended up getting CORS policy errors on this branch

**Comment by tiusty** [comment]
> image
> 
> I ended up getting CORS policy errors on this branch

I switched back to main and the iframes were able to load and I didn't get those errors. Then I switched back to that branch and got the same errors with the iframes not being able to load

I am using this URL, i.e the frontend canister URL
http://localhost:4943/?canisterId=ryjl3-tyaaa-aaaaa-aaaba-cai

**Comment by patnorris** [comment]
I'm also getting errors for localhost (actually my localhost setup doesn't work, I'm using the vite frontend with hot reloading). How does it look for you when you use npm run vite?

**Review by tiusty — APPROVED** [review]
Ended up working for me. On the npm run vite

**Pull request merged**
